server:
  port: 8086
spring:
  datasource:
    password: Password
    url: jdbc:mysql://localhost:3306/ekrushi?useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
